name: Reproduce `eza` bug

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Download `eza` v0.23.0
        run: curl --location --output eza.tar.gz https://github.com/eza-community/eza/releases/download/v0.23.0/eza_x86_64-unknown-linux-gnu.tar.gz

      - name: Extract `eza`
        run: tar xf eza.tar.gz

      - name: Populate current directory
        run: |
          touch foo bar baz
          mkdir hello goodbye

      - name: Run `ls` on current directory
        run: |
          echo '## `ls -la` output' >>"${GITHUB_STEP_SUMMARY}"
          echo '```' >>"${GITHUB_STEP_SUMMARY}"
          ls -la | tee -a "${GITHUB_STEP_SUMMARY}"
          echo '```' >>"${GITHUB_STEP_SUMMARY}"

      - name: Run `eza` on current directory
        run: |
          echo '## `./eza -la` output' >>"${GITHUB_STEP_SUMMARY}"
          echo '```' >>"${GITHUB_STEP_SUMMARY}"
          ./eza -la | tee -a "${GITHUB_STEP_SUMMARY}"
          echo '```' >>"${GITHUB_STEP_SUMMARY}"
